wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1685038452.603599
    t:
      1:
      - 55
      3:
      - 16
      - 23
      4: 3.8.13
      5: 0.13.9
      8:
      - 1
      - 5
epochs:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.01
